server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traplaner?serverTimezone=Asia/Seoul
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    #jsp view resolver setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB


file:
  upload:
    root-path: #?????????



# log level setting
logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug

#mybatis setting
mybatis:
  config-location: classpath:mybatis-config.xml

sns:
  kakao:
    Client-Id: ed255593c893c0dfdf69726766e4c8d9
    redirect-uri: http://localhost:8181/auth/kakao
    logout-redirect: http://localhost:8181

  naver:
    client-id: naver
    client-secret: naver
    redirect-uri: http://localhost:8181/oauth/naver
    logout-redirect: http://localhost:8181

#-------------------- ??? ?? ----------------------
# email ??
# email setting
 # spring.mail.host=smtp.gmail.com
 # spring.mail.port=587
 # spring.mail.username=??? ??? ??
 # spring.mail.password=2??? ? ????
 # spring.mail.properties.smtp.auth=true
 # spring.mail.properties.smtp.timeout=5000
 # spring.mail.properties.smtp.starttls.enable=true
 #
 # #??? ??? ?????
 # sns.kakao.app-key=????
 # sns.kakao.redirect-uri=http://localhost:8181/auth/kakao
 # sns.kakao.logout-redirect=http://localhost:8181
